name: Docker
run-name: ${{ github.actor }} is testing snakemake workflow ğŸš€
on: [push, pull_request]
 
jobs:
  skip_duplicates:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      actions: write
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          cancel_others: "true"
          concurrent_skipping: "same_content_newer"
          paths_ignore: '["**/README.md", "**/LICENSE"]'
  test_docker:
    runs-on: ubuntu-latest
    needs: skip_duplicates
    if: needs.skip_duplicates.should_skip != 'true'
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: .test/snakemake_env.yaml
          activate-environment: "snakemake"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: true
      - name: Install dependencies
        run: pip install 'snakemake==8.20.5' 'pulp'
      - name: Install apptainer
        run: sudo add-apt-repository -y ppa:apptainer/ppa && sudo apt-get update && sudo apt-get install -y apptainer
      - name: Run test pipeline
        run: snakemake --sdm apptainer conda -s workflow/Snakefile --directory .test --configfile config/config.yaml .test/targets.yaml -c2 
  test_docker_panaroo:
    runs-on: ubuntu-latest
    needs: skip_duplicates
    if: needs.skip_duplicates.should_skip != 'true'
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: .test/snakemake_env.yaml
          activate-environment: "snakemake"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: true
      - name: Install dependencies
        run: pip install 'snakemake==8.20.5' 'pulp'
      - name: Install apptainer
        run: sudo add-apt-repository -y ppa:apptainer/ppa && sudo apt-get update && sudo apt-get install -y apptainer
      - name: Run test pipeline
        run: snakemake --sdm apptainer conda -s workflow/Snakefile --directory .test --configfile .test/config_panaroo.yaml .test/targets.yaml -c2 
  test_docker_roary:
    runs-on: ubuntu-latest
    needs: skip_duplicates
    if: needs.skip_duplicates.should_skip != 'true'
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: .test/snakemake_env.yaml
          activate-environment: "snakemake"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: true
      - name: Install dependencies
        run: pip install 'snakemake==8.20.5' 'pulp'
      - name: Install apptainer
        run: sudo add-apt-repository -y ppa:apptainer/ppa && sudo apt-get update && sudo apt-get install -y apptainer
      - name: Run test pipeline
        run: snakemake --sdm apptainer conda -s workflow/Snakefile --directory .test --configfile .test/config_roary.yaml .test/targets.yaml -c2 
  test_docker_panacota:
    runs-on: ubuntu-latest
    needs: skip_duplicates
    if: needs.skip_duplicates.should_skip != 'true'
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: .test/snakemake_env.yaml
          activate-environment: "snakemake"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: true
      - name: Install dependencies
        run: pip install 'snakemake==8.20.5' 'pulp'
      - name: Install apptainer
        run: sudo add-apt-repository -y ppa:apptainer/ppa && sudo apt-get update && sudo apt-get install -y apptainer
      - name: Run test pipeline
        run: snakemake --sdm apptainer conda -s workflow/Snakefile --directory .test --configfile .test/config_panacota.yaml .test/targets.yaml -c2 